services:
  backend:
    build: ./backend
    container_name: reco-rss-backend
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
