services:
  main:
    build: ./service
    container_name: reco-rss-service
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
  experiments:
    build: ./experiments
    container_name: "reco-rss-workflows"
    volumes:
      - ./data:/app/data
