services:
  backend:
    build: ./backend
    container_name: reco-rss-backend
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - ./data:/srv
    ports:
      - 8080:80
    environment:
      - FB_NOAUTH=true
    restart: unless-stopped
