services:
  main:
    build: .
    container_name: lessrss
    ports:
      - 5000:5000
    volumes:
      - data:/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - ./src/app/__pycache__/
            - ./src/.venv/
volumes:
  data:
