services:
  main:
    build: ./src
    container_name: reco-rss
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
          ignore:
            - ./src/app/__pycache__/
            - ./src/.venv/
